### ISSUE TITLE
egui: text box and button moving upon "generate" button clicked in withdraw screen

### ISSUE THREAD

**Issue by mplatt8** [LayerTwo-Labs/thunder-rust#25]
https://github.com/user-attachments/assets/2a43ef3d-86be-47a7-a4fd-78864d0ffd6d

**Comment by Ash-L2L** [comment]
This is due to a bug in egui -
https://github.com/emilk/egui/issues/5500
https://github.com/emilk/egui/issues/5597

The bug is fixed in this PR https://github.com/emilk/egui/pull/5640, which should be merged in the next patch release
https://github.com/emilk/egui/milestone/5

**Comment by Ash-L2L** [comment]
Fixed in v0.11.7

**Comment by BTCapsule** [comment]
I still get this generate button bug. I found that the generate button moves when the text field is full, so maybe a longer text field could help

https://github.com/user-attachments/assets/2c5981b8-be64-473d-add4-bfdf1ce0db29
